# Generated by Django 5.2.15 on 2026-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('posicao', models.CharField(max_length=100, verbose_name='Posição')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('imagem', models.ImageField(upload_to='personagens/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Série')),
                ('estreia', models.CharField(max_length=4, verbose_name='Ano de Estreia')),
                ('genero', models.CharField(max_length=200, verbose_name='Gênero')),
                ('publico', models.CharField(max_length=100, verbose_name='Público-alvo')),
                ('estilo', models.CharField(max_length=255, verbose_name='Estilo')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
        migrations.CreateModel(
            name='SobreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('projeto', models.TextField(verbose_name='Sobre o Projeto')),
                ('tecnologias', models.CharField(max_length=200, verbose_name='Tecnologias Utilizadas')),
                ('desenvolvedora', models.CharField(max_length=100, verbose_name='Desenvolvedora')),
                ('instituicao', models.CharField(max_length=255, verbose_name='Instituição')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Informação Sobre',
                'verbose_name_plural': 'Informações Sobre',
            },
        ),
    ]
